application: testing-map-of-life
version: names
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: .*
  script: to_cartodb.application
