application: map-of-life
version: names
module: nomdb
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /taxonomy/names/static
  static_dir: static
- url: .*
  script: vneditor.application
