application: map-of-life
version: production
module: taxonomy
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /taxonomy/names/static
  static_dir: static
- url: /taxonomy/names/_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
- url: /taxonomy/.*
  script: vneditor.application
